apiVersion: v2
name: aiteza-frontend
description: A Helm chart for AITEZA Frontend
type: application
version: 1.10.1
appVersion: 1.10.1
icon: https://weyer-data-engineering.com/logos/AITEZA_bildlogo_1c_hellblau.svg