kind: Service
apiVersion: v1
metadata:
  name: {{ include "aiteza-backend.fullname" . }}
  labels:
    {{- include "aiteza-backend.labels" . | nindent 4 }}
  annotations: {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type | quote }}
  {{ if .Values.service.clusterIP -}}
  clusterIP: {{.Values.service.clusterIP}}
  {{- end }}
  selector: {{- include "aiteza-backend.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.httpPort }}
      targetPort: http
      name: http